spring:
  application:
    name: demo-server
  datasource:
    url: jdbc:h2:mem:demo
#    url: jdbc:h2:~/demo #User folder
#    url: jdbc:h2:file:./demo_db #Specific folder
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    contextPath: /
  port: 8080

logging:
  level:
    ROOT: info

# thread pool and queue size for processing contacts data
contacts:
  thread:
    timeout: 2
    core-pool: 10
    max-pool: 25
  queue:
    capacity: 25

cli-live-task:
  log-folder: ./logs